# Generated by Django 2.1.6 on 2019-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
