# Generated by Django 2.1.6 on 2019-03-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190310_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='hostname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Servers'),
        ),
    ]
