# Generated by Django 2.1.6 on 2019-03-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190310_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverdetails',
            options={'verbose_name_plural': 'ServerDetails'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'verbose_name_plural': 'Servers'},
        ),
    ]
